FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN powershell -Command \
    Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN powershell -Command choco install golang -y

ENV GOPATH C:\\gopath

RUN mkdir C:\\app
WORKDIR C:\\app

COPY . C:\\app

RUN go build -o myapp.exe

CMD ["C:\\app\\myapp.exe"]