# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, debian]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Cache Docker layers
      uses: actions/cache@v3.3.2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

#    - name: Build and run container
#      run: |
#        docker build -f Dockerfile.${{ matrix.os }} -t agent-${{ matrix.os }} .
#        docker run agent-${{ matrix.os }}

    - name: Build and run script
      run: |
        ./build.sh
        ./bin/1.0.0/agent-linux-amd64-1.0.0
