# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [ windowsv2019 ]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3.3.2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-    

    - name: Build and run script Windows
      run: |
        .\build.bat

    - name: Build ${{ matrix.os }}
      run: |
        docker build -f Dockerfile.${{ matrix.os }} -t agent-${{ matrix.os }} .
        docker run agent-${{ matrix.os }}